<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
  <?php require_once __DIR__ . '/../layouts/navbar.phtml'; ?>
<div class="container">
	<div class="jumbotron text-center">
		<h1>Go Law</h1>
		<h3>Cadastrar Produto</h3>
	</div>	

	<form method="POST" action="/criarProduto" enctype="multipart/form-data">
		<div class="form-group">
			<label>Nome:</label>
			<input 
				class="form-control" 
				type="text" 
				name="produto[nome]" 
				placeholder="Digite o nome do produto" 
				alt="Digite o nome do produto"
				required="true">	
		</div>
		<div class="form-group">
			<label>Valor:</label>
			<div class="input-group">
				<span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
				<input 
					class="form-control" 
					type="number" 
					name="produto[valor]" 
					placeholder="Digite o valor do produto" 
					alt="Digite o valor do produto">	
			</div>
		</div>
		
		<div class="form-group">
			<label>Descrição:</label>
			<div class="input-group">
				<span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
				<input 
					class="form-control" 
					type="text" 
					name="produto[descricao]" 
					placeholder="Digite a descrição" 
					alt="Digite a descrição">	
			</div>
		</div>
		
		<div class="form-group">
			<label>Foto:</label>
			<div class="input-group">
				<span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
				<input 
					class="form-control" 
					type="file" 
					name="fotoProduto" 
					placeholder="Clique para carregue a foto" 
					alt="Clique para selecionar a foto">	
			</div>
		</div>

		<div class="form-group">
			<button class="btn btn-primary">Cadastrar Produto</button>
		</div>
	</form>
</div>

</body>
</html>