 <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">GoLaw</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">Inicio</a></li>
          <li><a href="/clientes/">Clientes</a></li>
          <li><a href="/cadastrar-produto">Produtos</a></li>
        </ul>
      </div>
 </nav>